config/routes.rb
Rails.application.routes.draw do

  
  get '/search/free', to: 'search#free'

  get 'users/new'
  resources :bookings
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :courses
  resources :faculties
  resources :subjects
  resources :rooms
  resources :search
  resources :upload
  resources :uploader
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#index'


  
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :room
  has_many :subject, :dependent => :destroy
  has_many :course, :dependent => :destroy
  enum stafftype: [ :admin, :associate, :professor, :support]
  
 
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :authenticate_user!
  #before_action :ensure_admin, :only => [:edit, :destroy, :new]
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # def ensure_admin
  #   unless current_user && current_user.admin?
  #     render :text => "Access Error Message", :status => :unauthorized
  #   end
  # end
  
  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :school, :phonenumber, :email, :room_id, :stafftype)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school %>
  </div>

  <div class="field">
    <%= form.label :phonenumber %>
    <%= form.number_field :phonenumber %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.select :room_id, options_for_select(Room.all.map{|s|[s.name, s.id]}) %>
    <!--sets the room_id based the options from all the rooms names -->

  </div>

  <div class="field">
    <%= form.label :stafftype %>
    <%= form.select :stafftype, Faculty.stafftypes.keys %>
    <!-- sets the stafftype variable equal to the faculty model enum -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Room</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.school %></td>
        <td><%= faculty.phonenumber %></td>
        <td><%= faculty.email %></td>
        <td><%= faculty.room.name %></td>
        
        <td><%= faculty.stafftype %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @faculty.school %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @faculty.phonenumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @faculty.email %>
</p>

<p>
  <strong>Room:</strong>
  <%= @faculty.room %>
</p>

<p>
  <strong>Staff Type:</strong>
  <%= @faculty.stafftype %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>