config/routes.rb
Rails.application.routes.draw do

  
  get '/search/free', to: 'search#free'

  get 'users/new'
  resources :bookings
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :courses
  resources :faculties
  resources :subjects
  resources :rooms
  resources :search
  resources :upload
  resources :uploader
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#index'


  
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :faculty
    
    def printroom
        return "I am from room"
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  require 'rooms_decorator'
  before_action :authenticate_user!
  #before_action :ensure_admin, :only => [:edit, :destroy, :new]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  
  
  # def ensure_admin
  #   unless current_user && current_user.admin?
  #     render :text => "Access Error Message", :status => :unauthorized
  #   end
  # end

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @name = params[:room][:name]
    @floor = params[:room][:floor].to_s
    @seating = params[:room][:seating].to_s
    myRoom = BasicRoom.new(@room.name, @room.floor, @room.seating, @room)
    if params[:room][:projector].to_s.length > 0 then
      myRoom = RoomWithProjector.new(myRoom)
    end
    
    if params[:room][:computers].to_s.length > 0 then
      myRoom = RoomWithComputer.new(myRoom)
    end
    if params[:room][:Audio_enhancements].to_s.length > 0 then
      myRoom = RoomWithAudioEnhancements.new(myRoom)
    end
    
    @room.description = myRoom.details
    
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upload
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :floor, :seating)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :floor %>
    <%= form.text_field :floor %>
  </div>

  <div class="field">
    <%= form.label :seating %>
    <%= form.text_field :seating %>
  </div>

  <div class="field">
    Projector:
    <%= check_box_tag 'room[projector]', 'projector' %>
  </div>
  
  <div class="field">
    Computers:
    <%= check_box_tag 'room[computers]', 'computers' %>
  </div>
  
  <div class="field">
    Audio Enhancements:
    <%= check_box_tag 'room[Audio_enhancements]', 'Audio_enhancements' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
  
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Floor</th>
      <th>Seating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.floor %></td>
        <td><%= room.seating %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<p>
  <strong>Seating:</strong>
  <%= @room.seating %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>