config/routes.rb
Rails.application.routes.draw do

  
  get '/search/free', to: 'search#free'

  get 'users/new'
  resources :bookings
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :courses
  resources :faculties
  resources :subjects
  resources :rooms
  resources :search
  resources :upload
  resources :uploader
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#index'


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :subject
  belongs_to :subscriptions, optional: true
  belongs_to :course
  enum status: [ :pending, :approved, :rejected]
  enum starttime: [ :"8am", :"8:30am", :"9am", :"9:30am", :"10am", :"10:30am",:"11am", :"11:30am", :"12pm", :"12:30pm", :"1pm", :"1:30pm",  :"2pm", :"2:30pm", :"3pm", :"3:30pm", :"4pm", :"4:30pm", :"5pm", :"5:30pm", :"6pm", :"6:30pm", :"7pm", :"7:30pm", :"8pm", :"8:30pm", :"9pm", :"9:30pm"]
  enum duration: [ :"30 Minutes", :"1 Hour", :"1.5 Hours"]
  
  # def start_time
  #   self.date
  # end
  
  def details(x)
    detail = "A Booking has been #{x}: "
    self.attributes.each do |k,v|
      detail += "#{k}: #{v} --- "
    end
    return detail
  end
  
  def printdetails
    return "I am from print details"
  end
  
  
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :faculty, optional: true
  has_many :subject, :dependent => :destroy
  
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :room
  has_many :subject, :dependent => :destroy
  has_many :course, :dependent => :destroy
  enum stafftype: [ :admin, :associate, :professor, :support]
  
 
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :faculty
    
    def printroom
        return "I am from room"
    end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :course, optional: true, :dependent => :destroy
  belongs_to :faculty, optional: true, :dependent => :destroy
  belongs_to :subscriptions, optional: true, :dependent => :destroy
end

app/models/subscriptions.rb
class Subscriptions < ApplicationRecord
    has_many :bookings
    has_many :subject
    
   # @userbookings = Bookings.find_by( email: current_user.email)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  require 'rooms_decorator'
  before_action :authenticate_user!
  #before_action :ensure_admin, :only => [:edit, :destroy, :new]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  
  
  # def ensure_admin
  #   unless current_user && current_user.admin?
  #     render :text => "Access Error Message", :status => :unauthorized
  #   end
  # end

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @name = params[:room][:name]
    @floor = params[:room][:floor].to_s
    @seating = params[:room][:seating].to_s
    myRoom = BasicRoom.new(@room.name, @room.floor, @room.seating, @room)
    if params[:room][:projector].to_s.length > 0 then
      myRoom = RoomWithProjector.new(myRoom)
    end
    
    if params[:room][:computers].to_s.length > 0 then
      myRoom = RoomWithComputer.new(myRoom)
    end
    if params[:room][:Audio_enhancements].to_s.length > 0 then
      myRoom = RoomWithAudioEnhancements.new(myRoom)
    end
    
    @room.description = myRoom.details
    
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upload
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :floor, :seating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @cuemail = current_user.email
    @userbookings = Booking.find_by( email: @cuemail)
    
  end
  def show
    @user = User.find(params[:id])
    @name = @user.firstname
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="container">
      <div class="row">
        
      <p>Signed in as... <%= current_user.email %></p>
      (<%= link_to 'Sign out', destroy_user_session_path,:method => :delete%>)
     
      
      <% else %>
      <%= link_to'Register', new_user_registration_path %> or
      <%= link_to'Sign in', new_user_session_path %>
      </div>
      
      
      
       <!--<%= check_box"Admin Login", @au  %> -->
      
      
     <% end %>
     <div class="row">
     <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="<%=root_path%>">NCIRL Timetable</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="<%=root_path%>">Home</a></li>
            <li><a href="<%=rooms_path%>">Room</a></li>
            <li><a href="<%=faculties_path%>">Faculty</a></li>
            <li><a href="<%=courses_path%>">Course</a></li>
            <li><a href="<%=subjects_path%>">Subjects</a></li>
            <li><a href="<%=bookings_path%>">Booking</a></li>
            <li><a href="<%=search_index_path%>">Search</a></li>
            <li><a href="<%=users_new_path%>">Profile</a></li>
          </ul>
        </div>
      </nav>
      </div>
  
    <%=yield %>
        </div>

  </body>
</html>